### ISSUE TITLE
Clarify Pets fields -- checkbox vs text field in output

### ISSUE THREAD

**Issue by wslack** [Irma-Response/irma-api#27]
Right now, if "Pets" is unchecked for a shelter, the main site says "Pets Allowed? Unknown" Users putting in data may not realize that they need to do something else besides "leave box unchecked" when they know shelters aren't taking pets.

We should make the data a three-way selection - yes, no, and unknown.

**Comment by rogerroelofs** [comment]
How valuable is 'unknown' ?  Setting the db field to false when the box is not checked is easy enough.  Shelter data entry needs should dictate UI.  3 radios vs. select vs. the checkbox we have now.

**Comment by tabinfl** [comment]
Beyond complicating coding, this is where _we_ should reach out to the shelter and clarify the unknown. Don't want evacuees going on a wild goose chase for shelter.

**Comment by tabinfl** [comment]
Handled in https://github.com/Irma-Response/irma-api/pull/28

**Comment by wslack** [comment]
That's fine - as long as "unchecked" doesn't cause "unknown" to be published.

**Comment by rogerroelofs** [comment]
It doesn't.  Unknown was showing for pets being blank, not for the pets allowed checkbox.  After the deploy the map will show 'Yes' or 'No' with the text from the pets fields appended.
