### ISSUE TITLE
Expose shelter ID in json API 

### ISSUE THREAD

**Issue by jnolasco** [Irma-Response/irma-api#29]
Irmashelters.org says, "Doing so would allow us to linkback to you for user generated updates." i.e.
https://irma-api.herokuapp.com/shelters/846/edit (need the "846" or there's a bunch of hoops to jump through to get to the "846")

**Comment by roozbeh** [comment]
I'll take this one

**Comment by roozbeh** [comment]
The change is already applied. Waiting for deploy

**Comment by roozbeh** [comment]
This is resolved. Shelters have id now in the API response.
