### ISSUE TITLE
Include County field in search

### ISSUE THREAD

**Issue by tabinfl** [Irma-Response/irma-api#36]
Shelter search isn't using the County field, so only turns up records than mention the county name elsewhere.

Many Florida services are county-level, so this is more important here than it might be in other states.

**Comment by rogerroelofs** [comment]
Is this for the api data entry or the irmashelters.org map?

**Comment by rogerroelofs** [comment]
We will have to add the county column to the table to make it searchable.  Should I add but make hidden or just add (if so, where is preferred placement)?

**Comment by rogerroelofs** [comment]
County is currently in the list of hidden column names from f6958f65b1  Hide un-useful fields from yesterday.  I can easily remove it, but do we need to talk about it first?
