### ISSUE TITLE
Add fields and tidy up shelter list

### ISSUE THREAD

**Issue by DaynaW3990** [Irma-Response/irma-api#5]
The shelter list, https://irma-api.herokuapp.com/shelters , is used by data-entry volunteers to call or text shelters and update the least fresh shelters with new data.

This page has some usability problems and could use a couple new fields.

- [x] Columns Address Name, City, State, County, Zip, Google Place, Lat, Long, Notes do not add much to the list view and should be hidden
- [x] Add a private field with the name of the volunteer managing the County's info
- [x] Add a private field for Shelter staff SMS number

Later:

- [ ] Add a way to mass-export the all private email addresses

**Comment by ironcoconut** [comment]
Can you put special needs status in the notes field?
There is already a county for shelters.
Website can go in source or notes.
Shelters already have an updated_at column that shows when last updated.
For the private data, can you use the private notes field?

**Comment by DaynaW3990** [comment]
To be able to manage the data and know what needs to be updated, the fields need to be accepting, Name, timestamp. That way we can sort by time stamp and see who to call next.  With they fields buried at the end, or middle, they get lost, like I lost the time stamp.  
Special Needs really needs a check box so that on the map, it can be a filter. We are having to type it into the name so that the residents can find it, but it needs to be a functional map. 
If we can get the email and phone for texting fields separate, then we have someone who will write the bot to text update requests and email requesting updates.  We do not want to hand call each of the shelters for info daily!!!

**Comment by DaynaW3990** [comment]
Please test the user end to see what we are working with.  Search for all the shelter  in Pasco County and open the one that is the oldest.... Then you'll see how hard it is to find this data.  I want to thank you for having responded.  It's very hard to manage shelters in three states with the table in this order.  Thank you and I'm sorry.

**Comment by ironcoconut** [comment]
Got it. I will make the changes on harvey and get them pushed over.

**Comment by ironcoconut** [comment]
Nevermind. Apparently parts of this have already been tackled. I think one of the local admins should handle. I need a break anyways. I don't want to have to manage pushing to Harvey to push to Irma. Good luck guys. Ping me if you have code questions.

**Comment by rossettistone** [comment]
Partially resolved by https://github.com/Irma-Response/irma-api/pull/10. Just email export bit is outstanding. Is that still needed, or is the presence of the email and SMS info in the API sufficient for export at this point?

**Comment by tdooner** [comment]
Let's close this until we hear more need for the bulk email export. Thanks @rossettistone!
